title: ChipVerifyPro
description: AI-driven online learning platform for chip verification
theme: jekyll-theme-cayman

# Navigation
header_pages:
  - index.md
  - courses.md
  - blog.md
  - about.md
  - contact.md
  - privacy-policy.md
  
# Show excerpts on the home page
show_excerpts: true

# Google Analytics
google_analytics: G-3YBX1CYZNP

plugins:
  - jekyll-titles-from-headings
